### ISSUE TITLE
data.tar.gz and folds.tar.gz seems to be (almost) empty

### ISSUE THREAD

**Issue by lfoppiano** [glouppe/paper-author-disambiguation#14]
Hi, 
    I'm trying to have a look at the data provided, but the tar.gz files seems to be empty (just a text file). Github says they are not, it gives me 225 MB for data.tar.gz for example. 
Locally I get this: 

> Johan:data lfoppiano$ ls -lh
> total 24
> -rw-r--r--  1 lfoppiano  staff   1.7K Mar 18 10:44 README.md
> -rw-r--r--  1 lfoppiano  staff   134B Mar 18 10:44 data.tar.gz
> -rw-r--r--  1 lfoppiano  staff   133B Mar 18 10:44 folds.tar.gz

Thanks
Luca

**Comment by glouppe** [comment]
Can you retry cloning the repo? These files are stored on my LFS, for which the bandwidth is limited to 1GB/month. You may also need to install the LFS extension (see https://git-lfs.github.com).

**Comment by lfoppiano** [comment]
OK, so I've installed git-lfs, I've cloned the repository again. 

When I try to fetch, I get 'LFS is disabled for this repository':

> Johan:paper-author-disambiguation lfoppiano$ git-lfs fetch
> Fetching master
> Git LFS: (0 of 2 files) 0 B / 272.83 MB  
> Git LFS is disabled for this repository.
> Docs: https://github.com/contact
> Git LFS is disabled for this repository.
> Docs: https://github.com/contact

I tried to clone the whole repository with git-lfs but I've got the same result:

> Johan:disambiguation lfoppiano$ git-lfs clone git@github.com:glouppe/paper-author-disambiguation.git
> Cloning into 'paper-author-disambiguation'...
> remote: Counting objects: 695, done.
> remote: Total 695 (delta 0), reused 0 (delta 0), pack-reused 695
> Receiving objects: 100% (695/695), 5.14 MiB | 1.80 MiB/s, done.
> Resolving deltas: 100% (470/470), done.
> Checking connectivity... done.
> Git LFS: (0 of 2 files) 0 B / 272.83 MB  
> Git LFS is disabled for this repository.
> Docs: https://github.com/contact
> Git LFS is disabled for this repository.
> Docs: https://github.com/contact
> Johan:disambiguation lfoppiano$ 

Is this data the raw data from imspired.net or it has been preprocessed already? Maybe I can just download it from the source?

**Comment by glouppe** [comment]
I think my LFS account has been disabled because I ran out of bandwidth. Here is a mirror for the two files:

https://drive.google.com/open?id=0B1kJ1OjakiU4SW8tSkVTM0NtaE0
https://drive.google.com/open?id=0B1kJ1OjakiU4MGt3T1dMNlJ1Uk0

**Comment by lfoppiano** [comment]
Mercí beacoup!
