### ISSUE TITLE
results: the results for paper

### ISSUE THREAD

**Issue by MSusik** [glouppe/paper-author-disambiguation#3]
In this thread the results of disambiguation will be posted. I will post the mean from 3 scores, and the names of files, so that one can find the exact results.

If the name of clusters is `filewithclusters.json`, the name of the file with results will be `filewithclusters_results.json`. Both can be find under `/home/beard/results/`.

**Comment by MSusik** [comment]
`lnfi_balanced_ethnicity_<x>.json`
Last name, first initial strategy, all the features with ethnicity included. The classifier was gradient boosting.

| - | Precision | Recall | F-scores |
| --- | --- | :-: | --: |
| paired test | 0.9948 | 0.9738 | 0.9842 |
| paired train | 0.9976 | 0.9747 | 0.986 |
| paired overall | 0.9952 | 0.9739 | 0.9844 |
| b3 test | 0.9901 | 0.976 | 0.983 |
| b3 train | 0.997 | 0.979 | 0.9879 |
| b3 overall | 0.9907 | 0.9761 | 0.9834 |

**Comment by MSusik** [comment]
`lnfi_notbalanced_ethnicity_<x>.json`
Last name, first initial strategy, all the features with ethnicity included. The classifier was gradient boosting. Sampling was not balanced.

| - | Precision | Recall | F-scores |
| --- | --- | :-: | --: |
| paired test | 0.985 | 0.9707 | 0.9778 |
| paired train | 0.9879 | 0.9722 | 0.9799 |
| paired overall | 0.9854 | 0.9709 | 0.978 |
| b3 test | 0.9854 | 0.972 | 0.9786 |
| b3 train | 0.9925 | 0.9758 | 0.9841 |
| b3 overall | 0.986 | 0.9721 | 0.979 |

**Comment by MSusik** [comment]
`noblocking_ethnicity_<x>.json` 
Last name, first initial strategy, all the features with ethnicity included. The classifier was gradient boosting. Sampling without blocking.

| - | Precision | Recall | F-scores |
| --- | --- | :-: | --: |
| paired test | 0.9756 | 0.9629 | 0.9692 |
| paired train | 0.9775 | 0.9634 | 0.9704 |
| paired overall | 0.9758 | 0.963 | 0.9693 |
| b3 test | 0.9793 | 0.963 | 0.9711 |
| b3 train | 0.9853 | 0.9665 | 0.9758 |
| b3 overall | 0.9798 | 0.963 | 0.9713 |

**Comment by MSusik** [comment]
`dm_ethnicity_threshold_1_<x>.json`
Phonetic strategy with double metaphone used and splitting over the first given name initial. The classifier was gradient boosting.

| - | Precision | Recall | F-scores |
| --- | --- | :-: | --: |
| paired test | 0.9927 | 0.9817 | 0.9871 |
| paired train | 0.9979 | 0.9843 | 0.9911 |
| paired overall | 0.9934 | 0.982 | **0.9876** |
| b3 test | 0.9856 | 0.9827 | 0.9841 |
| b3 train | 0.9972 | 0.987 | 0.9921 |
| b3 overall | 0.9867 | 0.983 | **0.9848** |

**Comment by MSusik** [comment]
`dm_ethnicity_threshold_inf_<x>.json`
REMOVED - we will skip this setups (threshold_inf).

**Comment by MSusik** [comment]
`nysiis_ethnicity_threshold_1_<x>.json`
Phonetic strategy with nysiis used and splitting over the first given name initial. The classifier was gradient boosting.

| - | Precision | Recall | F-scores |
| --- | --- | :-: | --: |
| paired test | 0.9936 | 0.9814 | 0.9875 |
| paired train | 0.9982 | 0.9839 | 0.991 |
| paired overall | 0.9942 | 0.9818 | **0.9879** |
| b3 test | 0.9875 | 0.9826 | 0.985 |
| b3 train | 0.9977 | 0.9865 | 0.9921 |
| b3 overall | 0.9884 | 0.9828 | **0.9856** |

**Comment by MSusik** [comment]
`soundex_ethnicity_threshold_1_<x>.json`
Phonetic strategy with soundex used and splitting over the first given name initial. The classifier was gradient boosting.

| - | Precision | Recall | F-scores |
| --- | --- | :-: | --: |
| paired test | 0.9935 | 0.9725 | 0.9828 |
| paired train | 0.9979 | 0.9747 | 0.9862 |
| paired overall | 0.994 | 0.9727 | 0.9833 |
| b3 test | 0.9886 | 0.9745 | 0.9815 |
| b3 train | 0.9974 | 0.9791 | 0.9882 |
| b3 overall | 0.9894 | 0.9748 | 0.982 |

**Comment by MSusik** [comment]
`dm_noethnicity_threshold_1_<x>.json`
Phonetic strategy with double metaphone used and with splitting over the first given name initial. The classifier was gradient boosting. No ethnicity estimator.

| - | Precision | Recall | F-scores |
| --- | --- | :-: | --: |
| paired test | 0.9933 | 0.982 | 0.9877 |
| paired train | 0.9974 | 0.9838 | 0.9906 |
| paired overall | 0.9939 | 0.9823 | 0.988 |
| b3 test | 0.985 | 0.9825 | 0.9838 |
| b3 train | 0.9953 | 0.9858 | 0.9905 |
| b3 overall | 0.986 | 0.9827 | 0.9843 |

**Comment by MSusik** [comment]
`nysiis_noethnicity_threshold_1_<x>.json`
Phonetic strategy with nysiis used and splitting over the first given name initial. The classifier was gradient boosting. No ethnicity estimator.

| - | Precision | Recall | F-scores |
| --- | --- | :-: | --: |
| paired test | 0.9932 | 0.9814 | 0.9873 |
| paired train | 0.9973 | 0.9837 | 0.9904 |
| paired overall | 0.9937 | 0.9817 | 0.9877 |
| b3 test | 0.9861 | 0.982 | 0.9841 |
| b3 train | 0.9955 | 0.9856 | 0.9905 |
| b3 overall | 0.987 | 0.9822 | 0.9846 |

**Comment by MSusik** [comment]
`soundex_noethnicity_threshold_1_<x>.json`
Phonetic strategy with soundex used and splitting over the first given name initial. The classifier was gradient boosting.

| - | Precision | Recall | F-scores |
| --- | --- | :-: | --: |
| paired test | 0.9947 | 0.9739 | 0.9842 |
| paired train | 0.9976 | 0.9752 | 0.9863 |
| paired overall | 0.995 | 0.9741 | 0.9845 |
| b3 test | 0.9887 | 0.9755 | 0.9821 |
| b3 train | 0.9958 | 0.979 | 0.9873 |
| b3 overall | 0.9893 | 0.9756 | 0.9824 |

**Comment by glouppe** [comment]
Closing all these issues, as the paper is now completed. Thanks @MSusik for setting everything up and running these :)
