### ISSUE TITLE
results: feature importances

### ISSUE THREAD

**Issue by MSusik** [glouppe/paper-author-disambiguation#4]
[(0.12198469666666667, 'coauthors_similarity'),
 (0.07832377333333333, 'chinese'),
 (0.07368544, 'black'),
 (0.06895163, 'affiliation_similarity'),
 (0.06805375666666667, 'white'),
 (0.06773853, 'japanese'),
 (0.06699733333333334, 'other asian or pacific islander'),
 (0.06673571, 'other race, nec'),
 (0.06623908, 'american indian or alaska native'),
 (0.047468640000000006, 'author_full_name_similarity'),
 (0.04666712333333333, 'year_diff'),
 (0.04198797333333334, 'author_other_names_similarity'),
 (0.03856449666666667, 'keywords_similarity'),
 (0.036683523333333336, 'title_similarity'),
 (0.026030209999999998, 'subject_similairty'),
 (0.023049409999999996, 'author_first_given_name_similarity'),
 (0.02192508, 'journal_similarity'),
 (0.01651757666666667, 'abstract_similarity'),
 (0.009749913333333334, 'collaborations_similarity'),
 (0.007010633333333333, 'references_similarity'),
 (0.00437256, 'author_second_initial_similarity'),
 (0.0012628966666666666, 'author_second_given_name_similarity')]

**Comment by glouppe** [comment]
Closing all these issues, as the paper is now completed. Thanks @MSusik for setting everything up and running these :)
