### ISSUE TITLE
results: feature reduction

### ISSUE THREAD

**Issue by MSusik** [glouppe/paper-author-disambiguation#5]
Order of removing (the top one is the first removed, the bold was not removed as it was the last one):

`inspire-ml-01`:

author_second_given_name_similarity
author_second_initial_similarity
references_similarity
collaborations_similarity
abstract_similarity
journal_similarity
author_first_given_name_similarity
subject_similairty
title_similarity
author_other_names_similarity
year_diff
other_race
keywords_similarity
indian_or_american_native
white
japanese
author_full_name_similarity
affiliation_similarity
coauthors_similarity
black
asian_pacific_islander
**chinese**

`inspire-ml-02`

author_second_given_name_similarity
author_second_initial_similarity
collaborations_similarity
references_similarity
abstract_similarity
journal_similarity
author_first_given_name_similarity
subject_similairty
title_similarity
author_other_names_similarity
year_diff
keywords_similarity
indian_or_american_native
other_race
author_full_name_similarity
japanese
affiliation_similarity
black
coauthors_similarity
white
asian_pacific_islander
**chinese**

`inspire-ml-03`

author_second_given_name_similarity
author_second_initial_similarity
references_similarity
collaborations_similarity
abstract_similarity
author_first_given_name_similarity
journal_similarity
subject_similairty
title_similarity
author_other_names_similarity
year_diff
keywords_similarity
other_race
indian_or_american_native
author_full_name_similarity
japanese
affiliation_similarity
white
coauthors_similarity
black
asian_pacific_islander
**chinese**

The results files are called  `lnfi_feature_reduction_<x>.dat` where x is the number of features removed.

The results might me much more interesting in case of one of the phonetic algorithms.

The reduction took approximately 3 days.

**Comment by MSusik** [comment]
1 feature removed:

| - | Precision | Recall | F-scores |
| --- | --- | :-: | --: |
| paired test | 0.9944 | 0.9733 | 0.9837 |
| paired train | 0.9983 | 0.9754 | 0.9867 |
| paired overall | 0.9949 | 0.9736 | 0.9841 |
| b3 test | 0.9895 | 0.9758 | 0.9826 |
| b3 train | 0.9979 | 0.9801 | 0.9889 |
| b3 overall | 0.9903 | 0.9761 | 0.9831 |

**Comment by MSusik** [comment]
2 features removed:

| - | Precision | Recall | F-scores |
| --- | --- | :-: | --: |
| paired test | 0.9943 | 0.9736 | 0.9839 |
| paired train | 0.9986 | 0.9756 | 0.987 |
| paired overall | 0.9949 | 0.9739 | 0.9843 |
| b3 test | 0.9896 | 0.976 | 0.9828 |
| b3 train | 0.9982 | 0.9803 | 0.9892 |
| b3 overall | 0.9904 | 0.9763 | 0.9833 |

**Comment by MSusik** [comment]
3 features removed

| - | Precision | Recall | F-scores |
| --- | --- | :-: | --: |
| paired test | 0.9942 | 0.9737 | 0.9838 |
| paired train | 0.9986 | 0.9754 | 0.9869 |
| paired overall | 0.9948 | 0.9739 | 0.9842 |
| b3 test | 0.9895 | 0.976 | 0.9827 |
| b3 train | 0.9982 | 0.9802 | 0.9891 |
| b3 overall | 0.9903 | 0.9762 | 0.9832 |

**Comment by MSusik** [comment]
4 features removed

| - | Precision | Recall | F-scores |
| --- | --- | :-: | --: |
| paired test | 0.9934 | 0.9731 | 0.9832 |
| paired train | 0.9979 | 0.9752 | 0.9865 |
| paired overall | 0.994 | 0.9734 | 0.9836 |
| b3 test | 0.9891 | 0.9756 | 0.9823 |
| b3 train | 0.9978 | 0.9801 | 0.9889 |
| b3 overall | 0.9899 | 0.9759 | 0.9828 |

**Comment by MSusik** [comment]
5 features removed

| - | Precision | Recall | F-scores |
| --- | --- | :-: | --: |
| paired test | 0.9943 | 0.9734 | 0.9837 |
| paired train | 0.9986 | 0.9753 | 0.9868 |
| paired overall | 0.9948 | 0.9737 | 0.9841 |
| b3 test | 0.9896 | 0.9761 | 0.9828 |
| b3 train | 0.9982 | 0.9803 | 0.9891 |
| b3 overall | 0.9904 | 0.9763 | 0.9833 |

**Comment by MSusik** [comment]
6 features removed

| - | Precision | Recall | F-scores |
| --- | --- | :-: | --: |
| paired test | 0.994 | 0.9733 | 0.9836 |
| paired train | 0.9984 | 0.9752 | 0.9867 |
| paired overall | 0.9946 | 0.9736 | 0.984 |
| b3 test | 0.9893 | 0.9755 | 0.9823 |
| b3 train | 0.9981 | 0.9798 | 0.9889 |
| b3 overall | 0.9901 | 0.9758 | 0.9829 |

**Comment by MSusik** [comment]
7 features removed

| - | Precision | Recall | F-scores |
| --- | --- | :-: | --: |
| paired test | 0.994 | 0.973 | 0.9834 |
| paired train | 0.9979 | 0.9751 | 0.9864 |
| paired overall | 0.9945 | 0.9733 | 0.9838 |
| b3 test | 0.9891 | 0.9752 | 0.9821 |
| b3 train | 0.9977 | 0.9798 | 0.9886 |
| b3 overall | 0.9899 | 0.9754 | 0.9826 |

**Comment by MSusik** [comment]
8 features removed

| - | Precision | Recall | F-scores |
| --- | --- | :-: | --: |
| paired test | 0.9939 | 0.9733 | 0.9835 |
| paired train | 0.9982 | 0.9753 | 0.9866 |
| paired overall | 0.9944 | 0.9735 | 0.9839 |
| b3 test | 0.9888 | 0.975 | 0.9818 |
| b3 train | 0.9977 | 0.9797 | 0.9886 |
| b3 overall | 0.9896 | 0.9753 | 0.9824 |

**Comment by MSusik** [comment]
9 features removed

| - | Precision | Recall | F-scores |
| --- | --- | :-: | --: |
| paired test | 0.9942 | 0.9736 | 0.9838 |
| paired train | 0.9988 | 0.9757 | 0.9871 |
| paired overall | 0.9948 | 0.9738 | 0.9842 |
| b3 test | 0.9888 | 0.975 | 0.9819 |
| b3 train | 0.9982 | 0.9799 | 0.9889 |
| b3 overall | 0.9897 | 0.9752 | 0.9824 |

**Comment by MSusik** [comment]
10 features removed

| - | Precision | Recall | F-scores |
| --- | --- | :-: | --: |
| paired test | 0.9939 | 0.9736 | 0.9836 |
| paired train | 0.9986 | 0.9759 | 0.9871 |
| paired overall | 0.9945 | 0.9739 | 0.9841 |
| b3 test | 0.9886 | 0.9747 | 0.9816 |
| b3 train | 0.998 | 0.9799 | 0.9889 |
| b3 overall | 0.9895 | 0.975 | 0.9822 |

**Comment by MSusik** [comment]
11 features removed

| - | Precision | Recall | F-scores |
| --- | --- | :-: | --: |
| paired test | 0.9938 | 0.973 | 0.9833 |
| paired train | 0.9985 | 0.9754 | 0.9868 |
| paired overall | 0.9944 | 0.9733 | 0.9837 |
| b3 test | 0.9883 | 0.9741 | 0.9812 |
| b3 train | 0.9979 | 0.9795 | 0.9886 |
| b3 overall | 0.9893 | 0.9745 | 0.9818 |

**Comment by MSusik** [comment]
12 features removed

| - | Precision | Recall | F-scores |
| --- | --- | :-: | --: |
| paired test | 0.9939 | 0.9734 | 0.9836 |
| paired train | 0.9983 | 0.9756 | 0.9868 |
| paired overall | 0.9945 | 0.9737 | 0.984 |
| b3 test | 0.9882 | 0.9743 | 0.9812 |
| b3 train | 0.9976 | 0.9796 | 0.9885 |
| b3 overall | 0.9891 | 0.9746 | 0.9818 |

**Comment by MSusik** [comment]
13 features removed

| - | Precision | Recall | F-scores |
| --- | --- | :-: | --: |
| paired test | 0.9936 | 0.9735 | 0.9834 |
| paired train | 0.9982 | 0.9757 | 0.9868 |
| paired overall | 0.9942 | 0.9738 | 0.9839 |
| b3 test | 0.9879 | 0.974 | 0.9809 |
| b3 train | 0.9976 | 0.9796 | 0.9885 |
| b3 overall | 0.9889 | 0.9743 | 0.9815 |

**Comment by MSusik** [comment]
14 features removed

| - | Precision | Recall | F-scores |
| --- | --- | :-: | --: |
| paired test | 0.9937 | 0.9735 | 0.9835 |
| paired train | 0.9983 | 0.9757 | 0.9869 |
| paired overall | 0.9943 | 0.9738 | 0.9839 |
| b3 test | 0.9879 | 0.974 | 0.9809 |
| b3 train | 0.9976 | 0.9797 | 0.9885 |
| b3 overall | 0.9888 | 0.9744 | 0.9816 |

**Comment by MSusik** [comment]
15 features removed

| - | Precision | Recall | F-scores |
| --- | --- | :-: | --: |
| paired test | 0.9942 | 0.973 | 0.9834 |
| paired train | 0.9984 | 0.9751 | 0.9866 |
| paired overall | 0.9947 | 0.9732 | 0.9839 |
| b3 test | 0.9874 | 0.9722 | 0.9797 |
| b3 train | 0.9972 | 0.9782 | 0.9876 |
| b3 overall | 0.9883 | 0.9725 | 0.9804 |

**Comment by MSusik** [comment]
16 features removed

| - | Precision | Recall | F-scores |
| --- | --- | :-: | --: |
| paired test | 0.994 | 0.973 | 0.9834 |
| paired train | 0.9983 | 0.9752 | 0.9866 |
| paired overall | 0.9945 | 0.9733 | 0.9838 |
| b3 test | 0.987 | 0.9723 | 0.9796 |
| b3 train | 0.9971 | 0.9782 | 0.9875 |
| b3 overall | 0.9879 | 0.9726 | 0.9802 |

**Comment by MSusik** [comment]
17 features removed

| - | Precision | Recall | F-scores |
| --- | --- | :-: | --: |
| paired test | 0.991 | 0.9703 | 0.9805 |
| paired train | 0.9959 | 0.973 | 0.9843 |
| paired overall | 0.9916 | 0.9706 | 0.981 |
| b3 test | 0.9833 | 0.9677 | 0.9754 |
| b3 train | 0.9945 | 0.9748 | 0.9846 |
| b3 overall | 0.9843 | 0.9681 | 0.9761 |

**Comment by MSusik** [comment]
18 features removed

| - | Precision | Recall | F-scores |
| --- | --- | :-: | --: |
| paired test | 0.9888 | 0.9688 | 0.9787 |
| paired train | 0.9945 | 0.9721 | 0.9832 |
| paired overall | 0.9895 | 0.9692 | 0.9793 |
| b3 test | 0.981 | 0.9656 | 0.9732 |
| b3 train | 0.993 | 0.9732 | 0.983 |
| b3 overall | 0.982 | 0.966 | 0.9739 |

**Comment by MSusik** [comment]
19 features removed

| - | Precision | Recall | F-scores |
| --- | --- | :-: | --: |
| paired test | 0.9788 | 0.9679 | 0.9733 |
| paired train | 0.9845 | 0.9695 | 0.977 |
| paired overall | 0.9796 | 0.9681 | 0.9738 |
| b3 test | 0.9758 | 0.9605 | 0.9681 |
| b3 train | 0.9877 | 0.9685 | 0.978 |
| b3 overall | 0.9769 | 0.9607 | 0.9687 |

**Comment by MSusik** [comment]
20 features removed

| - | Precision | Recall | F-scores |
| --- | --- | :-: | --: |
| paired test | 0.9785 | 0.9672 | 0.9728 |
| paired train | 0.9842 | 0.9691 | 0.9766 |
| paired overall | 0.9792 | 0.9674 | 0.9733 |
| b3 test | 0.9751 | 0.9595 | 0.9672 |
| b3 train | 0.9873 | 0.9676 | 0.9773 |
| b3 overall | 0.9762 | 0.9597 | 0.9679 |

**Comment by MSusik** [comment]
only _chinese_ feature 

| - | Precision | Recall | F-scores |
| --- | --- | :-: | --: |
| paired test | 0.9751 | 0.9665 | 0.9708 |
| paired train | 0.9812 | 0.9681 | 0.9746 |
| paired overall | 0.9759 | 0.9667 | 0.9713 |
| b3 test | 0.9725 | 0.958 | 0.9652 |
| b3 train | 0.9844 | 0.9661 | 0.9751 |
| b3 overall | 0.9735 | 0.9582 | 0.9658 |

One interesting thing in this disambiguation is this statistics:

('Number of blocks =', 12978)
('True number of clusters', 15388)
('Number of computed clusters', 31413)

real    115m1.196s
user    1401m36.549s
sys     39m56.152s
 In `logs/<x>_<y>_d.log` you can see the estimated time for distance learning. x is number of features removed, y is the training set id (one per machine).

**Comment by glouppe** [comment]
Closing all these issues, as the paper is now completed. Thanks @MSusik for setting everything up and running these :)
